Update to CastXML 0.4.1
CastXML/CastXML-python-distributions pull request #9
Opened 2021-01-14 16:15 UTC by josephsnyder

2021-01-14 16:22 UTC, jcfr commented
Looks like the official release of CastXML is not based of the corresponding tag:

Here is the error reported on AppVeyor:

```
E           AssertionError: assert 'castxml vers...0113-gcbeee87' == 'castxml version 0.4.1'
E             - castxml version 0.4.20210113-gcbeee87
E             + castxml version 0.4.1
tests\test_distribution.py:16: AssertionError

```

2021-01-14 16:24 UTC, josephsnyder commented
Yep.  I was hoping to save some time by using a "master" build instead of the release but I'll just have to be patient.

2021-01-14 21:41 UTC, jcfr commented on CastXMLUrls.cmake
> +set(win64_binary_sha512 "c3c5a0c0a499c3128986a237bb8ea3d2f756aad68ebad69619f3a08014819b84e4bdad3fc179937ade941602b61feab3eba35ba804b9a5083362f6148c971f91")]
```suggestion
set(win64_binary_sha512 "c3c5a0c0a499c3128986a237bb8ea3d2f756aad68ebad69619f3a08014819b84e4bdad3fc179937ade941602b61feab3eba35ba804b9a5083362f6148c971f91")
```

2021-01-14 21:43 UTC, jcfr commented
I will have a look at the Python 3.x windows error

2021-01-26 15:31 UTC, jcfr commented
> re: appveyor failure

The file `enable-worker-remote-access.ps1` is made available by https://github.com/scikit-build/scikit-ci-addons here: https://github.com/CastXML/CastXML-python-distributions/blob/37c6977f009c34b9b891f2910cf5207c11d90f30/appveyor.yml#L45

Fixing `scikit-ci-addons` and making a new release of that project would address this, since this a project I maintain it should not be be an issue.

2021-01-26 15:34 UTC, jcfr commented
> Fixing `scikit-ci-addons` and making a new release of that project would address this, since this a project I maintain it should not be be an issue.

Update: It seems that `scikit-ci` is also having issue .. and this is a project we maintain also. See https://github.com/scikit-build/scikit-ci

2021-01-26 15:47 UTC, jcfr commented
> re: travis

I will another look later and report back

2021-01-26 15:49 UTC, jcfr commented
>  re: circleci

I just enabled this settings so that you see build results for manylinux:

![image](https://user-images.githubusercontent.com/219043/105868457-31e12700-5fc4-11eb-9535-db8522cf4b77.png)

2021-02-03 16:13 UTC, josephsnyder commented
@jcfr, Any thoughts about the Travis builds?

2021-02-10 14:05 UTC, jcfr requested changes
In addition, I suggest we update the test trying to install the wheel to use `--no-index`. See https://github.com/CastXML/CastXML-python-distributions/blob/2b0f0cd74975a30a21feae8bd6ca0201781a406f/tests/test_distribution.py#L27

2021-02-10 14:05 UTC, jcfr commented on .travis.yml
> +        - MACOSX_DEPLOYMENT_TARGET=10.15.2
```suggestion
```

2021-02-10 14:05 UTC, jcfr commented on .travis.yml
> +        - MACOSX_DEPLOYMENT_TARGET=10.15.2
```suggestion
```

2021-02-10 14:05 UTC, jcfr commented on .travis.yml
> +  - travis_wait 15 ci install
Add a comment explaining why this is needed

2021-02-10 14:05 UTC, jcfr commented on scikit-ci.yml
> +        SETUP_BDIST_WHEEL_ARGS: --plat-name macosx-10.15.2-x86_64
```suggestion
        SETUP_BDIST_WHEEL_ARGS: --plat-name macosx-10.13-x86_64
```

2021-02-10 14:18 UTC, josephsnyder commented on .travis.yml
> +  - travis_wait 15 ci install
It was originally "needed" during one of the interim runs when it seemed to time out there.  I've removed it in the current pull request.

2021-02-10 20:39 UTC, josephsnyder commented
I don't get why the `10.15.2` => `10.13` was what it needed, but @jcfr, you solved it!

I'll squash the commits and force push one more time.

2021-02-11 14:58 UTC, jcfr reviewed
Thanks for working on this :pray:

2021-02-11 14:58 UTC, jcfr commented on scikit-ci.yml
> +        CPPFLAGS: "-stdlib=libstdc++"
```suggestion
        # See https://scikit-build.readthedocs.io/en/latest/generators.html#libstdc-vs-libc
        CPPFLAGS: "-stdlib=libstdc++"
```

2021-02-11 14:58 UTC, jcfr commented on scikit-ci.yml
> +        SETUP_BDIST_WHEEL_ARGS: --plat-name macosx-10.13-x86_64
I couldn't find a website listing what could be the minimum target deployment for a given based SDK. Considered that `xcode12` Travis image is running `macOS 10.15.7` and bundles  `Xcode 12.0.1`    (see [here](https://docs.travis-ci.com/user/reference/osx#macos-version), targeting `10.13` seems "reasonable". 

If we get complains from users, we can re-assess to build wheel compatible with older system.

Also worth noting that macOS `10.13` is old enough to ensure the wheel will be installable in most of the current system:

![image](https://user-images.githubusercontent.com/219043/107652220-56890000-6c4e-11eb-8b8d-c36a78bab6b7.png)

![image](https://user-images.githubusercontent.com/219043/107652752-e9299f00-6c4e-11eb-8566-71b4f4e351be.png)

2021-02-11 14:59 UTC, jcfr commented
After the CI completes, let's squash and integrate.

2021-02-11 15:00 UTC, josephsnyder commented
I will do that.  Thanks again, JC

2021-02-11 15:54 UTC, jcfr commented
> I will do that. Thanks again, JC

Thanks. When squashing, could you add the following at the end of the commit message: `Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>`. For more details about this convention, see https://github.blog/2018-01-29-commit-together-with-co-authors/

2021-02-11 16:03 UTC, josephsnyder commented
Done

2021-02-11 16:05 UTC, merged